---
title: "MATH 327 Homework 7"
author: "Jaiden Atterbury"
date: "2024-05-15"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Note:** When I say something like Theorem/Definition 1.1.1, I mean, lecture 1 page 1 part 1 of the given definition or theorem. Furthermore, when I say something like Homework 1.1.1, I mean, homework 1, exercise 1, problem 1.

**Exercise 1.** Let $f$ be a continuous function on $\mathbb{R}$ such that $\lim_{x\to\infty}f(x)=L^{+}$ and $\lim_{x\to-\infty}f(x)=L^{-}$. Prove that for any real $c$ between $L^{+}$ and $L^{-}$, there exists $x\in\mathbb{R}$ such that $f(x)=c$.

**Proof:** Let $f$ be a continuous function on $\mathbb{R}$ such that $\lim_{x\to\infty}f(x)=L^{+}$ and $\lim_{x\to-\infty}f(x)=L^{-}$. Since $\lim_{x\to\infty}f(x)=L^{+}$, for all $\epsilon^{+}>0$, there exists an $N^{+}$, such that, if $x>N^{+}$, then $|f(x)-L^{+}|<\epsilon^{+}$, which implies that $L^{+}-\epsilon^{+}<f(x)<L^{+}+\epsilon^{+}$. Similarly, since $\lim_{x\to-\infty}f(x)=L^{-}$, for all $\epsilon^{-}>0$, there exists an $N^{-}$, such that, if $x<N^{-}$, then $|f(x)-L^{-}|<\epsilon^{-}$, which implies that $L^{-}-\epsilon^{-}<f(x)<L^{-}+\epsilon^{-}$.

Now, consider the three cases: $L^{-}<L^{+}$, $L^{-}=L^{+}$, and $L^{-}>L^{+}$. When $L^{-}=L^{+}$, the theorem doesn't hold (take the function $f(x)=e^{-x^2}$ for example), thus we only have the cases $L^{-}<L^{+}$and $L^{-}>L^{+}$. However, as noted in office hours, when $L^{-}>L^{+}$, we can work with $-f(x)$ and then we will be in the setting where $L^{-}<L^{+}$ (we can do this because the $x$ that makes $-f(x)=-c$ is the same $x$ that makes $f(x)=c$). Therefore, without loss of generality, we can assume that $L^{-}<L^{+}$.

Since we are assuming without loss of generality that $L^{-}<L^{+}$, then we must now pick a $c\in\mathbb{R}$, such that, $c$ is between $L^{-}$ and $L^{+}$. More concretely, we pick a $c\in\mathbb{R}$, such that, $L^{-}<c<L^{+}$. Since $L^{+}>c$, this implies that $L^{+}-c>0$. Now, since $\lim_{x\to\infty}f(x)=L^{+}$, for $\epsilon^{+}=L^{+}-c>0$, there exists an $N^{+}$, such that, if $x>N^{+}$, then $|f(x)-L^{+}|<L^{+}-c$, which implies that $L^{+}-L^{+}+c<f(x)<L^{+}+L^{+}-c$, and hence we can see that $c<f(x)$. Similarly, since $L^{-}<c$, this implies that $0<c-L^{-}$. Now, since $\lim_{x\to-\infty}f(x)=L^{-}$, for all $\epsilon^{-}=c-L^{-}>0$, there exists an $N^{-}$, such that, if $x<N^{-}$, then $|f(x)-L^{-}|<\epsilon^{-}$, which implies that $L^{-}-c+L^{-}<f(x)<L^{-}+c-L^{-}$, and hence we can see that $f(x)<c$.

Now, pick $a\in\mathbb{R}$, such that, $a<N^{-}$, then from the above derivations $f(a)<L^{-}+\epsilon^{-}=c$. Similarly, pick $b\in\mathbb{R}$, such that, $b>N^{+}$, then from the above derivations $f(b)>L^{+}-\epsilon^{+}=c$. Furthermore, since $f$ is continuous on $\mathbb{R}$, it is continuous on the closed and bounded interval $[a,b]$. Therefore, by the Intermediate Value Theorem, there exists an $x\in[a,b]$, such that, $f(x)=c$. Thus, since we assumed without loss of generality that $L^{-}<L^{+}$, it follows that, for all $c\in\mathbb{R}$ between $L^{-}$ and $L^{+}$, there exists an $x\in\mathbb{R}$ such that $f(x)=c$. $\square$

\newpage

**Exercise 2.** Prove that if $f$ is a continuous and positive function on $[0,1]$, then there exists $\delta>0$ such that $f(x)>\delta$ for any $x\in[0,1]$.

**Proof:** Let $f$ be a continuous and positive function on $[0,1]$. Since $f$ is continuous on a closed and bounded interval, that interval being $[0,1]$, it follows from the proof of the extreme value theorem that $f$ is bounded. However, the above fact isn't entirely needed, since we already know that $f(x)$ is positive on $[0,1]$, and this implies that $f(x)>0$ for all $x\in[0,1]$. Since $f(x)>0$ for all $x\in[0,1]$, it follows that $0$ is a lower bound for the set of images $\{f(x):x\in[0,1]\}$. Therefore, by the extreme value theorem, since $\{f(x):x\in[0,1]\}$ is bounded below, if the greatest lower bound of this set is $m>0$, then there exists an $x_m\in[0,1]$ such that $f(x_m)=m$. Furthermore, the extreme value theorem also states that $m$ is the minimum of $f$ on the interval $[0,1]$, which implies that, for all $x$, $f(x)\geq m$. Since for all $x\in[0,1]$, we have that $f(x)\geq m>0$, if we take $\delta=\frac{m}{2}>0$, then since $1>\frac{1}{2}>0$, this implies that $m>\frac{m}{2}>0$, and hence, for all $x\in[0,1]$, $f(x)>\delta=\frac{m}{2}>0$. Therefore, in conclusion, if $f$ is a continuous and positive function on $[0,1]$, then taking $\delta=\frac{m}{2}$, where $m$ is the greatest lower bound of $f$ on $[0,1]$, then for all $x\in[0,1]$, we have that $f(x)>\delta$. $\square$

\newpage

**Exercise 3**

1. Let $a>0$ be a positive real number. Is the function $f(x)=1/x$ uniformly continuous on $[a,\infty)$? Justify your answer.

If we let $a>0$ be a positive real number, then the function $f(x)=1/x$ is uniformly continuous on $[a,\infty)$. We will prove this claim below.

**Proof:** Let $\epsilon>0$. Choose $\delta=a^2\epsilon$, where $a>0$. Then $\forall x,y\in[a,\infty)$ with $|x-y|<\delta$, we must show that $|f(x)-f(y)|<\epsilon$, where $f(x)=\frac{1}{x}$. Consider $f(x)-f(y)$, since $f(x)=\frac{1}{x}$, this implies that $f(y)=\frac{1}{y}$. Thus we can see that $f(x)-f(y)=\frac{1}{x}-\frac{1}{y}=\frac{y-x}{xy}$. Since $x\geq a>0$ and $y\geq a>0$, it follows that $|f(x)-f(y)|=\frac{|y-x|}{xy}=\frac{|x-y|}{xy}$. Again, since $x\geq a>0$ and $y\geq a>0$, it follows that $0<\frac{1}{x}\leq\frac{1}{a}$ and $0<\frac{1}{y}\leq\frac{1}{a}$, and hence $0<\frac{1}{xy}\leq\frac{1}{a^2}$. Since we supposed that $|x-y|<\delta$ and found that $0<\frac{1}{xy}\leq\frac{1}{a^2}$, we can see that $|f(x)-f(y)|=\frac{|x-y|}{xy}\leq\frac{|x-y|}{a^2}<\frac{\delta}{a^2}=\frac{a^2\epsilon}{a^2}=\epsilon$. Thus, we can see that $|f(x)-f(y)|<\epsilon$. Hence, in conclusion, for all $\epsilon>0$, there exists a $\delta=a^2\epsilon$, such that, $\forall x,y\in[a,\infty)$ with $|x-y|<\delta$, then $|1/x-1/y|<\epsilon$. Thus we have shown that $f(x)=1/x$ is uniformly continuous on $[a,\infty)$. $\square$

2. Is $f(x)=1/x$ uniformly continuous on $(0,\infty)$?

The function $f(x)=1/x$ is not uniformly continuous on $(0,\infty)$. We will prove this claim below. Furthermore, since I found proofs using two different methods, I will showcase both of them.

**Proof 1:** Since the claim is that the function $f(x)=1/x$ is not uniformly continuous on $(0,\infty)$, then by the negation of the definition of uniform continuity, we must show that there exists an $\epsilon>0$, such that, for all $\delta>0$, there exists $x,y\in(0,\infty)$ that satisfy $|x-y|<\delta$, but $|f(x)-f(y)|\geq\epsilon$. Since we only have to show that there exists a single $\epsilon>0$ such that the above result holds, we will choose $\epsilon=1$. Now, for all $\delta>0$, we must show that there exists $x,y\in(0,\infty)$ that satisfies $|x-y|<\delta$, but has that $|f(x)-f(y)|\geq\epsilon$. Choose $x=\min(\delta,1)$, and $y=\frac{x}{2}$. Hence, since $\delta>0$ and $1>0$, we can see that $x>0$ and $y>0$, and thus $x,y\in(0,\infty)$. Furthermore, since $x=\min(\delta,1)$, this implies that $x\leq\delta$, which means that $|x-y|=|x-\frac{x}{2}|=|\frac{x}{2}|=\frac{x}{2}\leq\frac{\delta}{2}<\delta$. Therefore, we can see that $|x-y|<\delta$. Lastly, since $f(x)=\frac{1}{x}$ and $f(y)=\frac{1}{y}$, we can see that $|f(x)-f(y)|=|\frac{1}{x}-\frac{1}{y}|=|\frac{1}{x}-\frac{2}{x}|=|\frac{-1}{x}|=\frac{1}{x}$. However, since $x=\min(\delta,1)$, this implies that $x\leq1$, which means that $\frac{1}{x}\geq\frac{1}{1}=1$. Therefore, we can see that $|f(x)-f(y)|=\frac{1}{x}\geq1$. In conclusion, we have found for $\epsilon=1>0$ that, for all $\delta>0$, there exists an $x=\min(\delta,1)$ and $y=\frac{x}{2}$ in $(0,\infty)$, such that $|x-y|<\delta$, but $|f(x)-f(y)|\geq\epsilon=1$. The preceding line is exactly the definition that shows that the function $f(x)=1/x$ is not uniformly continuous on $(0,\infty)$. $\square$

**Proof 2:** Since the claim is that the function $f(x)=1/x$ is not uniformly continuous on $(0,\infty)$, then by the negation of the definition of uniform continuity (sequence version), it follows that we must find two sequences $u_n$ and $v_n$ on $(0,\infty)$, such that, $\lim_{n\to\infty}(u_n-v_n)=0$, but $\lim_{n\to\infty}(f(u_n)-f(v_n))\neq0$. Conveniently, since $I=(0,\infty)$, this implies that all of the natural numbers are in $I$. Thus, if we define $\forall n\in\mathbb{N}$, $u_n=\frac{1}{2n}$ and $v_n=\frac{1}{n}$, then we can see from Theorem 24.1 and Theorem 26.1 that $\lim_{n\to\infty}u_n=\lim_{n\to\infty}\frac{1}{2n}=0$ and $\lim_{n\to\infty}v_n=\lim_{n\to\infty}\frac{1}{n}=0$. Furthermore, since the limits are finite, we can use Theorem 24.2 and see that $\lim_{n\to\infty}(u_n-v_n)=\lim_{n\to\infty}u_n-\lim_{n\to\infty}v_n=0-0=0$. Now, since $f(x)=\frac{1}{x}$, it follows that $f(u_n)=\frac{1}{1/2n}=2n$ and $f(v_n)=\frac{1}{1/n}=n$, which implies that $f(u_n)-f(v_n)=2n-n=n$. Therefore, using Theorem 32.1, we can see that $\lim_{n\to\infty}(f(u_n)-f(v_n))=\lim_{n\to\infty}n=+\infty\neq0$. In conclusion, we defined the sequences $u_n=\frac{1}{2n}$ and $v_n=\frac{1}{n}$ on $(0,\infty)$, such that $\lim_{n\to\infty}(u_n-v_n)=0$, but $\lim_{n\to\infty}(f(u_n)-f(v_n))\neq0$. Therefore, by definition, the function $f(x)=1/x$ is not uniformly continuous on $(0,\infty)$. $\square$

\newpage

**Exercise 4.** Prove that the function $f(x)=\sqrt{x}$ is uniformly continuous on the interval $[3,\infty)$.

Since I have found two simple proofs that each use a different $\delta$ value, I will showcase them both below.

**Proof 1:** Let $\epsilon>0$. Choose $\delta=2\sqrt{3}\epsilon$. Then $\forall x,y\in[3,\infty)$ with $|x-y|<\delta$, we must show that $|f(x)-f(y)|<\epsilon$, where $f(x)=\sqrt{x}$. Consider $f(x)-f(y)$, since $f(x)=\sqrt{x}$, this implies that $f(y)=\sqrt{y}$. Thus we can see that $f(x)-f(y)=\sqrt{x}-\sqrt{y}=\frac{(\sqrt{x}-\sqrt{y})(\sqrt{x}+\sqrt{y})}{\sqrt{x}+\sqrt{y}}=\frac{x-y}{\sqrt{x}+\sqrt{y}}$. Since $x\geq3$ and $y\geq3$, this implies that $\sqrt{x}\geq\sqrt{3}>0$ and $\sqrt{y}\geq\sqrt{3}>0$, and therefore it follows that $|f(x)-f(y)|=\frac{|x-y|}{\sqrt{x}+\sqrt{y}}$. Furthermore, since it was shown above that $\sqrt{x}\geq\sqrt{3}>0$ and $\sqrt{y}\geq\sqrt{3}>0$, this implies that $\sqrt{x}+\sqrt{y}\geq\sqrt{3}+\sqrt{3}=2\sqrt{3}$. Hence we can see that $\frac{1}{\sqrt{x}+\sqrt{y}}\leq\frac{1}{2\sqrt{3}}$. Since we supposed that $|x-y|<\delta$ and found that $\frac{1}{\sqrt{x}+\sqrt{y}}\leq\frac{1}{2\sqrt{3}}$, we can see that $|f(x)-f(y)|=\frac{|x-y|}{\sqrt{x}+\sqrt{y}}\leq\frac{|x-y|}{2\sqrt{3}}<\frac{\delta}{2\sqrt{3}}=\frac{2\sqrt{3}\epsilon}{2\sqrt{3}}=\epsilon$. Thus, we can see that $|f(x)-f(y)|<\epsilon$. Hence, in conclusion, for all $\epsilon>0$, there exists a $\delta=2\sqrt{3}\epsilon$, such that, $\forall x,y\in[3,\infty)$ with $|x-y|<\delta$, then $|\sqrt{x}-\sqrt{y}|<\epsilon$. Thus we have shown that $f(x)=\sqrt{x}$ is uniformly continuous on $[3,\infty)$. $\square$

**Proof 2:** Let $\epsilon>0$. Choose $\delta=\epsilon$. Then $\forall x,y\in[3,\infty)$ with $|x-y|<\delta$, we must show that $|f(x)-f(y)|<\epsilon$, where $f(x)=\sqrt{x}$. Consider $f(x)-f(y)$, since $f(x)=\sqrt{x}$, this implies that $f(y)=\sqrt{y}$. Thus we can see that $f(x)-f(y)=\sqrt{x}-\sqrt{y}=\frac{(\sqrt{x}-\sqrt{y})(\sqrt{x}+\sqrt{y})}{\sqrt{x}+\sqrt{y}}=\frac{x-y}{\sqrt{x}+\sqrt{y}}$. Since $x\geq3$ and $y\geq3$, this implies that $\sqrt{x}\geq\sqrt{3}>0$ and $\sqrt{y}\geq\sqrt{3}>0$, and therefore it follows that $|f(x)-f(y)|=\frac{|x-y|}{\sqrt{x}+\sqrt{y}}$. Furthermore, since it was shown above that $\sqrt{x}\geq\sqrt{3}>0$ and $\sqrt{y}\geq\sqrt{3}>0$, this implies that $\sqrt{x}+\sqrt{y}\geq\sqrt{3}+\sqrt{3}=2\sqrt{3}>1$. Hence we can see that $\frac{1}{\sqrt{x}+\sqrt{y}}\leq\frac{1}{2\sqrt{3}}<1$. Since we supposed that $|x-y|<\delta$ and found that $\frac{1}{\sqrt{x}+\sqrt{y}}<1$, we can see that $|f(x)-f(y)|=\frac{|x-y|}{\sqrt{x}+\sqrt{y}}\leq|x-y|<\delta=\epsilon$. Thus, we can see that $|f(x)-f(y)|<\epsilon$. Hence, in conclusion, for all $\epsilon>0$, there exists a $\delta=\epsilon$, such that, $\forall x,y\in[3,\infty)$ with $|x-y|<\delta$, then $|\sqrt{x}-\sqrt{y}|<\epsilon$. Thus we have shown that $f(x)=\sqrt{x}$ is uniformly continuous on $[3,\infty)$. $\square$

\newpage

**Exercise 5.** Let $f$ be a uniformly continuous function on an interval $I$. Let $g$ be a uniformly continuous function on an interval $J$. Assume that $f(I)\subset J$. Prove that the composition $g(f(x))$ is a uniformly continuous function on $I$. Remark: $f(I)$ is the set of all the images of elements of $I:f(I)=\{f(x),x\in I\}$.

**Proof:** Let $\epsilon>0$. Since $g$ is a uniformly continuous function on $J$, for all $\epsilon_g>0$, there exists a $\delta_g>0$, such that, for all $a,b\in J$ satisfying $|a-b|<\delta_g$, then $|g(a)-g(b)|<\epsilon_g$. Since this holds for all $\epsilon_g$, take $\epsilon_g=\epsilon>0$. Then, there exists a $\delta_g>0$, such that, for all $a,b\in J$ satisfying $|a-b|<\delta_g$, then $|g(a)-g(b)|<\epsilon$. Furthermore, since $f$ is a uniformly continuous function on $I$, for all $\epsilon_f>0$, there exists a $\delta_f>0$, such that, for all $x,y\in I$ satisfying $|x-y|<\delta_f$, then $|f(x)-f(y)|<\epsilon_f$. Since this holds for all $\epsilon_f$, take $\epsilon_f=\delta_g>0$. Then, there exists a $\delta_f>0$, such that, for all $x,y\in I$ satisfying $|x-y|<\delta_f$, then $|f(x)-f(y)|<\delta_g$. However, since $f(I)\subset J$, it follows that $f(x),f(y)\in J$. Therefore, $f(x)$ and $f(y)$ are elements in $J$ such that $|f(x)-f(y)|<\delta_g$, and hence $|g(f(x))-g(f(y))|<\epsilon$. Therefore, for all $\epsilon>0$, there exists a $\delta=\delta_f$, such that, for all $x,y\in I$ satisfying $|x-y|<\delta$, then $|g(f(x))-g(f(y))|<\epsilon$. Thus we have shown that $g(f(x))$ is a uniformly continuous function on $I$. $\square$
