---
title: "MATH 327 Homework 5"
author: "Jaiden Atterbury"
date: "2024-05-06"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

**Note:** When I say something like Theorem/Definition 1.1.1, I mean, lecture 1 page 1 part 1 of the given definition or theorem. Furthermore, when I say something like Homework 1.1.1, I mean, homework 1, exercise 1, problem 1.

**Exercise 1.** Let $\sum^\infty_{n=1}a_n$ and $\sum^\infty_{n=1}b_n$ be 2 convergent series, and let $c$ be a real number.

1. Prove that the series $\sum^\infty_{n=1}a_n+b_n$ is convergent and $\sum^\infty_{n=1}a_n+\sum^\infty_{n=1}b_n=\sum^\infty_{n=1}a_n+b_n$.

**Proof:** $\\$
Since $\sum^\infty_{n=1}a_n$ and $\sum^\infty_{n=1}b_n$ are two convergent series, we know that they converge to two real numbers $A$ and $B$, respectively. That is $\sum^\infty_{n=1}a_n=A$ and $\sum^\infty_{n=1}b_n=B$. Furthermore, if we define the partial sums of $\sum^\infty_{n=1}a_n$ and $\sum^\infty_{n=1}b_n$ as $A_n=\sum^n_{k=1}a_k$ and $B_n=\sum^n_{k=1}b_k$, then from the definition of series convergence we know $\lim_{n\to\infty}A_n=\lim_{n\to\infty}\sum^n_{k=1}a_k=A$ and $\lim_{n\to\infty}B_n=\lim_{n\to\infty}\sum^n_{k=1}b_k=B$.

Now, if we define $c_n=a_n+b_n$, then $\sum^\infty_{n=1}c_n=\sum^\infty_{n=1}a_n+b_n$. Furthermore, we can define the sequence of partial sums of this series as $C_n=\sum^n_{k=1}c_k=\sum^n_{k=1}a_k+b_k=\sum^n_{k=1}a_k+\sum^n_{k=1}b_k$, where the last equality holds since the summation is finite. Taking the limit of the sequence $C_n$ we can see that
\begin{align*}
\lim_{n\to\infty}C_n &= \lim_{n\to\infty}\sum^n_{k=1}c_k \\
&= \lim_{n\to\infty}\left(\sum^n_{k=1}a_k+\sum^n_{k=1}b_k\right) \quad \text{(Since $\sum^n_{k=1}c_k=\sum^n_{k=1}a_k+\sum^n_{k=1}b_k$)} \\
&= \lim_{n\to\infty}\left(A_n+B_n\right) \quad \text{(Since $A_n=\sum^n_{k=1}a_k$ and $B_n=\sum^n_{k=1}b_k$)} \\
&= \lim_{n\to\infty}A_n+\lim_{n\to\infty}B_n \quad \text{(By Theorem 24.2 on the midterm study guide)}\\
&= A+B \quad \text{(Since $\lim_{n\to\infty}A_n=A$ and $\lim_{n\to\infty}B_n=B$)} \\
&= \sum^\infty_{n=1}a_n+\sum^\infty_{n=1}b_n \quad \text{(Since $\sum^\infty_{n=1}a_n=A$ and $\sum^\infty_{n=1}b_n=B$)}
\end{align*}
Thus, since the limit of the partial sums is finite, it follows that $\sum^\infty_{n=1}c_n=\sum^\infty_{n=1}a_n+b_n$ is convergent. Furthermore, we know that this series is convergent to $A+B$, which as defined above is equal to $\sum^\infty_{n=1}a_n+\sum^\infty_{n=1}b_n$. $\square$

It is important to note that the final equality is merely saying that the series of partial sums of $\sum^\infty_{n=1}a_n+b_n$ converges to the same limit as the sum of the limits of the sequence of partial sums of $\sum^\infty_{n=1}a_n$ and $\sum^\infty_{n=1}b_n$.

2. Prove that the series $\sum^\infty_{n=1}ca_n$ is convergent and $\sum^\infty_{n=1}ca_n=c(\sum^\infty_{n=1}a_n)$.

**Proof:** $\\$
Since $\sum^\infty_{n=1}a_n$ is a convergent series, we know that it converges to a real number $A$. That is $\sum^\infty_{n=1}a_n=A$. Furthermore, if we define the partial sums of $\sum^\infty_{n=1}a_n$ as $A_n=\sum^n_{k=1}a_k$, then from the definition of series convergence we know $\lim_{n\to\infty}A_n=\lim_{n\to\infty}\sum^n_{k=1}a_k=A$.

Now, if we define $d_n=ca_n$, then $\sum^\infty_{n=1}d_n=\sum^\infty_{n=1}ca_n$. Furthermore, we can define the sequence of partial sums of this series as $D_n=\sum^n_{k=1}d_k=\sum^n_{k=1}ca_k=c\sum^n_{k=1}a_k$, where the last equality holds since the summation is finite. Taking the limit of the sequence $D_n$ we can see that
\begin{align*}
\lim_{n\to\infty}D_n &= \lim_{n\to\infty}\sum^n_{k=1}d_k \\
&= \lim_{n\to\infty}\left(c\sum^n_{k=1}a_k\right) \quad \text{(Since $\sum^n_{k=1}d_k=c\sum^n_{k=1}a_k$)} \\
&= \lim_{n\to\infty}\left(cA_n\right) \quad \text{(Since $A_n=\sum^n_{k=1}a_k$)} \\
&= c\lim_{n\to\infty}A_n \quad \text{(By Theorem 24.1 on the midterm study guide)}\\
&= cA \quad \text{(Since $\lim_{n\to\infty}A_n=A$)} \\
&= c\left(\sum^\infty_{n=1}a_n\right) \quad \text{(Since $\sum^\infty_{n=1}a_n=A$)}
\end{align*}
Thus, since the limit of the partial sums is finite, it follows that $\sum^\infty_{n=1}d_n=\sum^\infty_{n=1}ca_n$ is convergent. Furthermore, we know that this series is convergent to $cA$, which as defined above is equal to $c\left(\sum^\infty_{n=1}a_n\right)$. $\square$

It is important to note that the final equality is merely saying that the series of partial sums of $\sum^\infty_{n=1}ca_n$ converges to the same limit as $c$ times the limit of the sequence of partial sums of $\sum^\infty_{n=1}a_n$.

\newpage

**Exercise 2.** Let $\sum^\infty_{n=1}a_n$ be a series with non-negative terms.

1. Prove that if the series $\sum^\infty_{n=1}a_n$ is divergent, then $\sum^\infty_{n=1}a_n=+\infty$.

**Proof:** $\\$
Let $\sum^\infty_{n=1}a_n$ be a series with non-negative terms. Furthermore, let $A_n=\sum^n_{k=1}a_k$ be the sequence of partial sums corresponding to the series $\sum^\infty_{n=1}a_n$. If the series $\sum^\infty_{n=1}a_n$ is divergent, by the contrapositive of Theorem (Tool) from slide 4 of the series lecture slides, it follows that $A_n$ is not bounded. Since $A_n$ is not bounded, this means that the sequence either doesn't have an upper-bound, doesn't have a lower-bound, or both. However, it was also proven in Theorem (Tool) from slide 4 of the series lecture slides, that if $\sum^\infty_{n=1}a_n$ is a series with non-negative terms, then $A_n$ is a monotonically increasing sequence. Therefore, by the definition of a monotonically increasing sequence, $a_1\leq a_n$ for all $n$. Therefore $a_1$ is a lower bound for $A_n$. Since $A_n$ is not bounded, this implies that $A_n$ does not have an upper bound. Since $A_n$ is a monotonically increasing sequence that is not bounded above, by Theorem 32.1 from the midterm study guide, it follows that $\lim_{n\to\infty}A_n=+\infty$. Lastly, since $\lim_{n\to\infty}A_n=+\infty$, by the definition of series convergence and divergence, it follows that $\sum^\infty_{n=1}a_n=+\infty$. $\square$

2. Does the result still hold if we don't assume that the sequence $a_n$ is non-negative? Prove your claim.

After considering the case where we don't assume that the sequence $a_n$ is non-negative, I believe that the above result does not hold. To prove that this result does not hold, we will provide a proof by counterexample.

**Proof:** $\\$
(Proof by counterexample) Consider the series $\sum^\infty_{n=0}(-1)^n$. Let $a_n=(-1)^n$ be the sequence that is being summed over. As proven in Lecture 6, $a_n=(-1)^n$ is divergent. In particular, $\lim_{n\to\infty}a_n=\lim_{n\to\infty}(-1)^n$ does not exist (since the values of $a_n$ oscillates from $1$ to $-1$ infinitely). Since $a_n$ takes on the value 1 for even $n$ and the value $-1$ for odd $n$, it follows that $a_n=(-1)^n$ is not non-negative for all $n$. Furthermore, since $\lim_{n\to\infty}a_n\neq0$, by the divergence test, it follows that $\sum^\infty_{n=0}(-1)^n$ diverges.

Now that we have obtained a divergent series that is not non-negative for all $n$, we must show that this series does not diverge to $+\infty$. In order to show that this result holds for our given series, we must consider the sequence of partial sums $S_n=\sum^n_{k=0}(-1)^k$. In particular we will show that $S_n$ can only take on the values $1$ and $0$. Specifically, when $n$ is even, $S_n$ is 1, and when $n$ is odd, $S_n$ is $0$. We will prove this result using induction. This is done below.

Consider the proposition, "$\mathcal{P}(n)$: if $n$ is even, $S_n=1$, and if $n$ is odd, $S_n=0$." We wish to show that this holds for all non-negative integers (that is $n\geq0$ such that $n\in\mathbb{Z}$). With that being said, this implies that our base case is for $n=0$, and as we can see that $S_0=\sum^0_{k=0}a_k=\sum^0_{k=0}(-1)^k=(-1)^0=1$. Therefore $\mathcal{P}(1)$ is true, and hence our base case holds. We now must show that if we assume $\mathcal{P}(n)$ is true, then $\mathcal{P}(n+1)$ must also be true. Assuming $\mathcal{P}(n)$ is true equates to assuming that, if $n$ is even, $S_n=1$, and if $n$ is odd, $S_n=0$. We will first consider the case where $n+1$ is even, which implies that $n$ is odd, and hence by our inductive hypothesis, $S_n=0$. Furthermore, if we notice that $S_{n+1}=S_n+(-1)^{n+1}=0+1=1$, then we can see that $\mathcal{P}(n+1)$ is true in this case. Lastly, we will now consider the case where $n+1$ is odd, which implies that $n$ is even, and hence by our inductive hypothesis, $S_n=1$. Furthermore, if we notice that $S_{n+1}=S_n+(-1)^{n+1}=1+(-1)=0$, then $\mathcal{P}(n+1)$ is true in this case as well. Therefore, if we assume that $\mathcal{P}(n)$ is true, it follows that $\mathcal{P}(n+1)$ is also true. Thus, by mathematical induction, $\mathcal{P}(n)$ holds for all $n\geq0$.

Therefore we have shown that $S_n$, the sequence of partial sums can only take on the values 0 and 1. By the definition of a bounded sequence, this implies that $1$ is an upper bound to the sequence $S_n$ (and is actually the least upper bound), and $0$ is a lower bound to the sequence $S_n$ (and is actually the greatest lower bound). Therefore $S_n$ is a bounded sequence, and is also a divergent sequence (since $\sum^\infty_{n=0}(-1)^n$ being divergent implies that $S_n$ is also divergent). All that is left to show is that $S_n$ does not diverge to infinity.

However, based on the definition of the infinite limit of a sequence, all we have to do is find an $A\in\mathbb{R}$ such that, for all $N$, $\exists n>N$, such that $A\geq S_n$. Consider $A=2$ (any $A\geq1$ would work), then for all $n$, it follows that $A=2>a_n$. The last inequality holds because $S_n\in\{0,1\}$ for all $n$. Therefore, by definition, $S_n$ does not diverge to $+\infty$, and thus, by the definition of series convergence and divergence, $\sum^\infty_{n=0}(-1)^n$ does not diverge to $+\infty$. Therefore we have found a divergent series that is not non-negative for all $n$ that does not diverge to $+\infty$. Thus, we have shown that the result from part 1 does not hold if we don't assume that the sequence $a_n$ is non-negative. $\square$

Note that any series consisting of all negative terms that is monotonically decreasing would also work as a counterexample.

\newpage

**Exercise 3.** Are the following series convergent, divergent:

1. $\sum^\infty_{n=1}\frac{n+\sqrt{n}+1}{n^2(1+\sqrt{n})+3}$

In order to determine if $\sum^\infty_{n=1}\frac{n+\sqrt{n}+1}{n^2(1+\sqrt{n})+3}$ is convergent or divergent, since the divergence test gave us no information, we will try a different strategy of testing for convergence or divergence. Namely, we will look at the $n$th term of the sequence. That is, we will look at $u_n=\frac{n+\sqrt{n}+1}{n^2(1+\sqrt{n})+3}$. Since $n+\sqrt{n}+1>0$ and $n^2(1+\sqrt{n})+3>0$, it follows that $u_n=\frac{n+\sqrt{n}+1}{n^2(1+\sqrt{n})+3}>0$. Thus, we will be able to use the Comparison test (inequality version). This procedure is done below.

Since $\sqrt{n}\leq n$ and $1\leq n$, this implies that $n+\sqrt{n}+1\leq n+n+n$. Similarly, since $n^2+3>0$, this implies that $n^2\sqrt{n}+n^2+3>n^2\sqrt{n}$. The previous two results imply that $\frac{n+\sqrt{n}+1}{n^2\sqrt{n}+n^2+3}<\frac{n+n+n}{n^2\sqrt{n}}$. Therefore, we can see that the $n$th term of the sequence is smaller than the following
$$\frac{n+\sqrt{n}+1}{n^2(1+\sqrt{n})+3}=\frac{n+\sqrt{n}+1}{n^2\sqrt{n}+n^2+3}<\frac{n+n+n}{n^2\sqrt{n}}=\frac{3n}{n^2n^{1/2}}=\frac{3}{n^{3/2}}.$$
By the p-test proved in Homework 4 and in lecture, we know that $\sum\frac{1}{n^{3/2}}$ is convergent since $p=3/2>1$. Furthermore, by Homework 5.1.2, it follows that $\sum\frac{3}{n^{3/2}}$ is also convergent. Therefore, since $\sum\frac{3}{n^{3/2}}$ is a convergent series of positive terms, $\sum\frac{n+\sqrt{n}+1}{n^2(1+\sqrt{n})+3}$ is a series of positive terms, and $\frac{n+\sqrt{n}+1}{n^2(1+\sqrt{n})+3}<\frac{3}{n^{3/2}}$ for all $n$, by the Comparison test (inequality version), it follows that the series $\sum^\infty_{n=1}\frac{n+\sqrt{n}+1}{n^2(1+\sqrt{n})+3}$ is also convergent. $\square$

2. $\sum^\infty_{n=1}\frac{(-1)^n}{\sqrt{n^2+n+1}}$. For this series, determine also whether the series is absolutely convergent, conditionally convergent, or divergent.

To start, we will determine if $\sum^\infty_{n=1}\frac{(-1)^n}{\sqrt{n^2+n+1}}$ is convergent or divergent. Since the even and odd subsequences of $u_n=\frac{(-1)^n}{\sqrt{n^2+n+1}}$ both converged to $0$, we will have to look for a different strategy of testing for convergence or divergence. The appearance of the $(-1)^n$ in the numerator tells us that we should try the Alternating series test. This procedure is done below.

First, we will start by checking if the sign of $u_n$ alternates between each term. Since $\sqrt{n^2+n+1}>0$ for all $n$, the sign of $u_n=\frac{(-1)^n}{\sqrt{n^2+n+1}}$ is controlled by $(-1)^n$. When $n$ is even, the sign is positive, and when $n$ is odd, the sign is negative. Thus, the sign of $u_n$ alternates between terms.

Next, we will check if the sequence $|u_n|$ is non-increasing/decreasing. Since $u_n=\frac{(-1)^n}{\sqrt{n^2+n+1}}$, it follows that $|u_n|=|\frac{(-1)^n}{\sqrt{n^2+n+1}}|=\frac{1}{\sqrt{n^2+n+1}}$. Now, we must show that $|u_{n+1}|\leq|u_n|$. Notice that $|u_n|=\frac{1}{\sqrt{n^2+n+1}}$ and $|u_{n+1}|=\frac{1}{\sqrt{(n+1)^2+n+1+1}}=\frac{1}{\sqrt{n^2+2n+1+n+2}}=\frac{1}{\sqrt{n^2+3n+3}}$. Since $3n+3=3(n+1)>n+1$, it follows that $n^2+3n+3>n^2+n+1$, this implies that $\sqrt{n^2+3n+3}>\sqrt{n^2+n+1}$, and hence $\frac{1}{\sqrt{n^2+3n+3}}<\frac{1}{\sqrt{n^2+n+1}}$. Therefore, the sequence $|u_n|$ is non-increasing/decreasing.

Lastly, we will check if $\lim_{n\to\infty}|u_n|=0$. As shown above, $|u_n|=\frac{1}{\sqrt{n^2+n+1}}$. In office hours, we were told that we could use any result from calculus about limits to compute limits for series. With that being said, since the degree of the polynomial is greater in the denominator, it follows that the limit of $|u_n|$ converges to $0$. Namely, $\lim_{n\to\infty}|u_n|=\lim_{n\to\infty}\frac{1}{\sqrt{n^2+n+1}}=0$. Therefore, we have shown $\lim_{n\to\infty}|u_n|=0$.

Since we have shown that the above three properties hold, by the Alternating series test, $\sum^\infty_{n=1}\frac{(-1)^n}{\sqrt{n^2+n+1}}$ is a convergent series. Now we will try and see if $\sum^\infty_{n=1}\frac{(-1)^n}{\sqrt{n^2+n+1}}$ is absolutely convergent, or just conditionally convergent. This will be done by assessing the convergence of $\sum^\infty_{n=1}|u_n|=\sum^\infty_{n=1}\frac{1}{\sqrt{n^2+n+1}}$. In the above Alternating series test we showed that $\lim_{n\to\infty}|u_n|=0$, therefore the divergence test gives us no information. Thus, we will try a different strategy of testing for convergence or divergence. Namely, we will look at the $n$th term of the sequence. That is, we will look at $|u_n|=\frac{1}{\sqrt{n^2+n+1}}$.

Since $n\leq n^2$ and $1\leq n^2$, it follows that $n^2+n+1\leq n^2+n^2+n^2=3n^2$, this implies that $\sqrt{n^2+n+1}\leq\sqrt{3n^2}=\sqrt{3}n$, and therefore we can see that $\frac{1}{\sqrt{n^2+n+1}}\geq\frac{1}{\sqrt{3}n}$. In office hours, we were told that we could use the following fact without proof: if $\sum a_n$ diverges, then $A\sum a_n$, where $A$ is a constant, diverges as well. Since we have shown in lecture that $\sum\frac{1}{n}$ diverges, it follows that $\sum\frac{1}{\sqrt{3}n}$ also diverges. Therefore, since $\sum\frac{1}{\sqrt{3}n}$ is a divergent series of positive terms, $\sum\frac{1}{\sqrt{n^2+n+1}}$ is a series of positive terms, and $\frac{1}{\sqrt{3}n}<\frac{1}{\sqrt{n^2+n+1}}$ for all $n$, by the Comparison test (inequality version), it follows that the series $\sum^\infty_{n=1}|u_n|=\sum^\infty_{n=1}\frac{1}{\sqrt{n^2+n+1}}$ is divergent. Therefore, the series $\sum^\infty_{n=1}\frac{(-1)^n}{\sqrt{n^2+n+1}}$ is conditionally convergent. $\square$  

3. $\sum^\infty_{n=1}\frac{(2n+3)^4}{(n^2+n+5)^3}$

In order to determine if $\sum^\infty_{n=1}\frac{(2n+3)^4}{(n^2+n+5)^3}$ is convergent or divergent, since the divergence test gave us no information, we will try a different strategy of testing for convergence or divergence. Namely, we will look at the $n$th term of the sequence. That is, we will look at $u_n=\frac{(2n+3)^4}{(n^2+n+5)^3}$. Since $(2n+3)^4>0$ and $(n^2+n+5)^3>0$, it follows that $u_n=\frac{(2n+3)^4}{(n^2+n+5)^3}>0$. Thus, we will be able to use the Comparison test (inequality version). This procedure is done below.

Since $3\leq3n$, this implies that $2n+3\leq2n+3n$, and thus we can see that $(2n+3)^4\leq(2n+3n)^4$. Similarly, since $n+5>0$, this implies that $n^2+n+5>n^2$, and thus we can see that $(n^2+n+5)^3>(n^2)^3$. The previous two results imply that $\frac{(2n+3)^4}{(n^2+n+5)^3}<\frac{(2n+3n)^4}{(n^2)^3}$. Therefore, we can see that the $n$th term of the sequence is smaller than the following
$$\frac{(2n+3)^4}{(n^2+n+5)^3}<\frac{(2n+3n)^4}{(n^2)^3}=\frac{(5n)^4}{n^6}=\frac{5^4n^4}{n^6}=\frac{5^4}{n^2}.$$
As proven in Homework 2.2 and by the p-test proven in lecture, we know that $\sum\frac{1}{n^{2}}$ is convergent since $p=2>1$. Furthermore, by Homework 5.1.2, it follows that $\sum\frac{5^4}{n^{2}}$ is also convergent. Therefore, since $\sum\frac{5^4}{n^{2}}$ is a convergent series of positive terms, $\sum\frac{(2n+3)^4}{(n^2+n+5)^3}$ is a series of positive terms, and $\frac{(2n+3)^4}{(n^2+n+5)^3}<\frac{5^4}{n^{2}}$ for all $n$, by the Comparison test (inequality version), it follows that the series $\sum^\infty_{n=1}\frac{(2n+3)^4}{(n^2+n+5)^3}$ is also convergent. $\square$

4. $\sum^\infty_{n=1}\frac{n^25^n}{3^n+3^{2n}}$

In order to determine if $\sum^\infty_{n=1}\frac{n^25^n}{3^n+3^{2n}}$ is convergent or divergent, since the divergence test gave us no information, we will try a different strategy of testing for convergence or divergence. Namely, we will look at the $n$th term of the sequence. That is, we will look at $u_n=\frac{n^25^n}{3^n+3^{2n}}=\frac{n^25^n}{3^n(3^{n}+1)}$. Since $n^25^n>0$ and $3^n(3^{n}+1)>0$, it follows that $u_n=\frac{n^25^n}{3^n+3^{2n}}=\frac{n^25^n}{3^n(3^{n}+1)}>0$. Thus, we will be able to use the Ratio test (limit version). To perform the Ratio test (limit version) we will take the limit of $\frac{u_{n+1}}{u_n}$. Before we do this we will compute $\frac{u_{n+1}}{u_n}$. This is done below.
$$\frac{u_{n+1}}{u_n}=\frac{\frac{(n+1)^25^{n+1}}{3^{n+1}(3^{n+1}+1)}}{\frac{n^25^n}{3^n(3^{n}+1)}}=\frac{(n+1)^25^{n+1}}{3^{n+1}(3^{n+1}+1)}\cdot\frac{3^n(3^n+1)}{n^25^n}=\frac{5(n^2+2n+1)5^{n}}{3\cdot3^{n}(3^{n+1}+1)}\cdot\frac{3^n(3^n+1)}{n^25^n}=\frac{5n^2+10n+5}{3n^2}\cdot\frac{3^n+1}{3^{n+1}+1}.$$
Now that we have found $\frac{u_{n+1}}{u_n}$, we will continue simplifying to get it into a form that we can easily use our limit theorems proved in lecture. Simplifying further we can see that
$$\frac{u_{n+1}}{u_n}=\frac{5n^2+10n+5}{3n^2}\cdot\frac{3^n+1}{3^{n+1}+1}=\frac{5+\frac{10}{n}+\frac{5}{n^2}}{3}\cdot\frac{1+\frac{1}{3^n}}{3+\frac{1}{3^n}}=\frac{5+\frac{10}{n}+\frac{5}{n^2}}{3}\cdot\frac{1+\left(\frac{1}{3}\right)^n}{3+\left(\frac{1}{3}\right)^n}.$$
We will now take the limit of $\frac{u_{n+1}}{u_n}$. In this derivation, we will use Theorem 24.1, Theorem 24.2, and Theorem 24.3 (Operation on limits) from the midterm study guide in order to break up the limit. Furthermore, we will use Theorem 26.1 and Theorem 26.2.1 to show that the terms involving $n$ in the above expression for $\frac{u_{n+1}}{u_n}$ all go to zero. Taking this limit we see that
$$\lim_{n\to\infty}\frac{u_{n+1}}{u_n}=\frac{\lim_{n\to\infty}5+10\lim_{n\to\infty}\frac{1}{n}+5\lim_{n\to\infty}\frac{1}{n^2}}{\lim_{n\to\infty}3}\cdot\frac{\lim_{n\to\infty}1+\lim_{n\to\infty}\left(\frac{1}{3}\right)^n}{\lim_{n\to\infty}3+\lim_{n\to\infty}\left(\frac{1}{3}\right)^n}=\frac{5+0+0}{3}\cdot\frac{1+0}{3+0}=\frac{5}{9}.$$
As shown above, $\lim_{n\to\infty}\frac{u_{n+1}}{u_n}=\frac{5}{9}$, however, by Theorem 35 from the midterm study guide, this implies that $\lim\sup\left(\frac{u_{n+1}}{u_n}\right)=\frac{5}{9}$. Therefore, since $\lim\sup\left(\frac{u_{n+1}}{u_n}\right)=\frac{5}{9}<1$, by the Ratio test (limit version), the series $\sum^\infty_{n=1}\frac{n^25^n}{3^n+3^{2n}}$ is convergent. $\square$

5. $\sum^\infty_{n=1}\frac{(-1)^n(n+2)}{5n+4}$. For this series, determine also whether the series is absolutely convergent, conditionally convergent, or divergent.

In order to determine if $\sum^\infty_{n=1}\frac{(-1)^n(n+2)}{5n+4}$ is absolutely convergent, conditionally convergent, or divergent, we will start by using the divergence test. Namely, we will check if $\lim_{n\to\infty}\frac{(-1)^n(n+2)}{5n+4}\neq0$.

To show that $\lim_{n\to\infty}\frac{(-1)^n(n+2)}{5n+4}\neq0$, we will show that the sequence itself is not convergent in the first place. To show that the sequence $u_n=\frac{(-1)^n(n+2)}{5n+4}$ is not convergent, we will use the contrapositive of Theorem 40 from the midterm study guide, which states that, if there exists subsequences that converge to different limits, then the original sequence is divergent.

First, consider the subsequence of all of the terms with even indices. The terms in this subsequence take the form
$$u_{2n}=\frac{(-1)^{2n}(2n+2)}{5(2n)+4}=\frac{2n+2}{10n+4}=\frac{2+\frac{2}{n}}{10+\frac{4}{n}}.$$
Applying the limit laws from Theorem 24 from the midterm study guide, we can see that $\lim_{n\to\infty}u_{2n}=\frac{2+0}{10+0}=\frac{2}{10}=\frac{1}{5}$.

On the other hand, if we consider the subsequence of all of the terms with odd indices, then the terms in this subsequence take the form
$$u_{2n-1}=\frac{(-1)^{2n-1}(2n-1+2)}{5(2n-1)+4}=\frac{-(2n+1)}{10n-5+4}=\frac{-2n-1}{10n-1}=\frac{-2-\frac{1}{n}}{10-\frac{1}{n}}.$$
Applying the limit laws from Theorem 24 from the midterm study guide, we can see that $\lim_{n\to\infty}u_{2n-1}=\frac{-2-0}{10-0}=\frac{-2}{10}=\frac{-1}{5}$.

Since we have found two subsequences that converge to two different limits, we can use the contrapositive of Theorem 40 from the midterm study guide and say that $u_n=\frac{(-1)^n(n+2)}{5n+4}$ is not convergent, and is thus not equal to zero. Since $\lim_{n\to\infty}\frac{(-1)^n(n+2)}{5n+4}\neq0$, by the divergence test, the series $\sum\limits^{\infty}_{n=1}\frac{(-1)^n(n+2)}{5n+4}$ is divergent. $\square$

Note that, since $\sum u_n=\sum\frac{(-1)^n(n+2)}{5n+4}$ is divergent, by the contrapositive of the Absolute convergence theorem, it turns out that $\sum|u_n|=\sum\frac{n+2}{5n+4}$ is also divergent (I don't know if this is necessary, but I included it anyway).
